version: '3.7'
services:

  game:
    image: registry.gitlab.com/adam-zielonka-pro/dos-pascal-docker
    working_dir: /project
    volumes: [ ./:/project ]
    command: [ src/DESKA.PAS, --watch ]

  caddy:
    image: caddy
    volumes: [./:/usr/share/caddy/]
    ports: [ 5001:80 ]
